ALTER TABLE `order`
ADD COLUMN `parent` INT(10) UNSIGNED DEFAULT NULL AFTER `status`,
ADD INDEX `parent_idx` (`parent` ASC);

ALTER TABLE `order` 
ADD CONSTRAINT `parent_relation` FOREIGN KEY (`parent`)
  REFERENCES `order` (`id`) MATCH SIMPLE
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;